Import gettext-0.19.8.1

diff --git a/gettext-tools/tests/autopoint-1 b/gettext-tools/tests/autopoint-1
--- a/gettext-tools/tests/autopoint-1
+++ b/gettext-tools/tests/autopoint-1
@@ -5,14 +5,14 @@
 
 : ${AUTOCONF=autoconf}
 ${AUTOCONF} --version >/dev/null 2>/dev/null \
-  || { echo "Skipping test: autoconf not found"; exit 77; }
+  || { echo "Skipping test: autoconf not found"; Exit 77; }
 
 cat <<\EOF >configure.ac
 AC_PREREQ([2.60])
 EOF
 
 ${AUTOCONF} >/dev/null 2>/dev/null \
-  || { echo "Skipping test: autoconf version too old"; exit 77; }
+  || { echo "Skipping test: autoconf version too old"; Exit 77; }
 
 rm -f configure.ac
 
@@ -23,11 +23,11 @@ export gettext_datadir
 
 # no configure.ac
 $gettext_datadir/autopoint 2>&1 | grep 'Missing configure.in or configure.ac' 2>&1 >/dev/null \
-    || exit 1
+    || Exit 1
 
-test ! -d intl || exit 1
-test ! -d m4 || exit 1
-test ! -d po || exit 1
+test ! -d intl || Exit 1
+test ! -d m4 || Exit 1
+test ! -d po || Exit 1
 
 # configure.ac without AM_GNU_GETTEXT_VERSION
 cat <<\EOF >configure.ac
@@ -41,11 +41,11 @@ AC_OUTPUT
 EOF
 
 $gettext_datadir/autopoint 2>&1 | grep 'Missing version' 2>&1 >/dev/null \
-    || exit 1
+    || Exit 1
 
-test ! -d intl || exit 1
-test ! -d m4 || exit 1
-test ! -d po || exit 1
+test ! -d intl || Exit 1
+test ! -d m4 || Exit 1
+test ! -d po || Exit 1
 
 # VERSION specified through intl/VERSION file, but in wrong format
 cat <<\EOF >configure.ac
@@ -62,10 +62,10 @@ test -d intl || mkdir intl
 echo bogus-version > intl/VERSION
 
 $gettext_datadir/autopoint 2>&1 | grep 'Missing version' 2>&1 >/dev/null \
-    || exit 1
+    || Exit 1
 
-test ! -d m4 || exit 1
-test ! -d po || exit 1
+test ! -d m4 || Exit 1
+test ! -d po || Exit 1
 
 # VERSION specified through intl/VERSION file
 cat <<\EOF >configure.ac
@@ -84,15 +84,15 @@ echo gettext-0.15 > intl/VERSION
 
 # For further investigation, autopoint keeps autopoint.diff in $TMPDIR
 # if there is a mismatch.  Set TMPDIR not to pollute /tmp.
-TMPDIR="$PWD" $gettext_datadir/autopoint 2>&1 | grep 'locally modified' 2>&1 >/dev/null || exit 1
+TMPDIR="$PWD" $gettext_datadir/autopoint 2>&1 | grep 'locally modified' 2>&1 >/dev/null || Exit 1
 
-test ! -d m4 || exit 1
-test ! -d po || exit 1
+test ! -d m4 || Exit 1
+test ! -d po || Exit 1
 
 echo 'GNU gettext library from gettext-0.15' > intl/VERSION
 
-TMPDIR="$PWD" $gettext_datadir/autopoint 2>&1 || exit 1
+TMPDIR="$PWD" $gettext_datadir/autopoint 2>&1 || Exit 1
 
 rm -fr intl
 
-exit 0
+Exit 0
diff --git a/gettext-tools/tests/lang-bash b/gettext-tools/tests/lang-bash
--- a/gettext-tools/tests/lang-bash
+++ b/gettext-tools/tests/lang-bash
@@ -33,8 +33,8 @@ ${XGETTEXT} -o prog.tmp --omit-header --no-location prog.bash \
   >prog.err 2>&1
 result=$?
 cat prog.err | grep -v 'warning: the syntax \$"\.\.\." is deprecated due to security reasons'
-test $result = 0 || { exit 1; }
-LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
+test $result = 0 || { Exit 1; }
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || Exit 1
 
 cat <<\EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
@@ -48,7 +48,7 @@ msgstr[1] ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} prog.ok prog.pot || exit 1
+${DIFF} prog.ok prog.pot || Exit 1
 
 cat <<\EOF > fr.po
 msgid ""
@@ -68,11 +68,11 @@ msgstr[1] "$n morceaux de gateau"
 EOF
 
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
-LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || Exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || Exit 1
 
 : ${DIFF=diff}
-${DIFF} fr.po fr.po.new || exit 1
+${DIFF} fr.po fr.po.new || Exit 1
 
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
@@ -82,10 +82,10 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of bash version 2.0 or newer.
 (bash -c :) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: bash not found"; exit 77; }
+  || { echo "Skipping test: bash not found"; Exit 77; }
 case `bash -c 'echo $BASH_VERSION'` in
   [2-9].*) ;;
-  *) echo "Skipping test: bash version too old"; exit 77;;
+  *) echo "Skipping test: bash version too old"; Exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
@@ -96,7 +96,7 @@ if test $LOCALE_FR != none; then
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
@@ -104,7 +104,7 @@ if test $LOCALE_FR_UTF8 != none; then
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
@@ -113,18 +113,18 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  exit 77
+  Exit 77
 fi
 
 case "$host_os" in
   darwin*)
     if test $LOCALE_FR != none; then
       LC_ALL=$LOCALE_FR bash --help \
-        | grep '^Utilisation' > /dev/null 2>&1 || exit 77
+        | grep '^Utilisation' > /dev/null 2>&1 || Exit 77
     fi
     if test $LOCALE_FR_UTF8 != none; then
       LC_ALL=$LOCALE_FR_UTF8 bash --help \
-        | grep '^Utilisation' > /dev/null 2>&1 || exit 77
+        | grep '^Utilisation' > /dev/null 2>&1 || Exit 77
     fi
   ;;
 esac
@@ -148,23 +148,23 @@ EOF
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
   prepare_locale_ fr $LOCALE_FR
-  LANGUAGE= LC_ALL=$LOCALE_FR bash ./prog.bash 2 > prog.out || exit 1
+  LANGUAGE= LC_ALL=$LOCALE_FR bash ./prog.bash 2 > prog.out || Exit 1
   : ${DIFF=diff}
   ${DIFF} prog.nok prog.out > /dev/null && {
     echo "Skipping test: bash is built without i18n support"
-    exit 77
+    Exit 77
   }
-  ${DIFF} prog.ok prog.out || exit 1
+  ${DIFF} prog.ok prog.out || Exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
   prepare_locale_ fr $LOCALE_FR_UTF8
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 bash ./prog.bash 2 > prog.out || exit 1
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 bash ./prog.bash 2 > prog.out || Exit 1
   : ${DIFF=diff}
   ${DIFF} prog.nok prog.out > /dev/null && {
     echo "Skipping test: bash is built without i18n support"
-    exit 77
+    Exit 77
   }
-  ${DIFF} prog.oku prog.out || exit 1
+  ${DIFF} prog.oku prog.out || Exit 1
 fi
 
-exit 0
+Exit 0
diff --git a/gettext-tools/tests/lang-guile b/gettext-tools/tests/lang-guile
--- a/gettext-tools/tests/lang-guile
+++ b/gettext-tools/tests/lang-guile
@@ -22,8 +22,8 @@ cat <<\EOF > prog.scm
 EOF
 
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.tmp --omit-header --no-location prog.scm || exit 1
-LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.scm || Exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || Exit 1
 
 cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
@@ -41,7 +41,7 @@ msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} prog.ok prog.pot || exit 1
+${DIFF} prog.ok prog.pot || Exit 1
 
 cat <<\EOF > fr.po
 msgid ""
@@ -66,11 +66,11 @@ msgstr "~1@*~A remplace ~0@*~A."
 EOF
 
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
-LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || Exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || Exit 1
 
 : ${DIFF=diff}
-${DIFF} fr.po fr.po.new || exit 1
+${DIFF} fr.po fr.po.new || Exit 1
 
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
@@ -80,10 +80,10 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of guile version 1.7 or newer.
 (guile --version) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: guile not found"; exit 77; }
+  || { echo "Skipping test: guile not found"; Exit 77; }
 case `guile --version | sed -e 1q | sed -e 's/^[^0-9]*//'` in
   0.* | 1.[0-6] | 1.[0-6].* )
-    echo "Skipping test: guile version too old"; exit 77;;
+    echo "Skipping test: guile version too old"; Exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
@@ -94,7 +94,7 @@ if test $LOCALE_FR != none; then
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
@@ -102,7 +102,7 @@ if test $LOCALE_FR_UTF8 != none; then
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
@@ -111,7 +111,7 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  exit 77
+  Exit 77
 fi
 
 : ${DIFF=diff}
@@ -130,15 +130,15 @@ EOF
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
   prepare_locale_ fr $LOCALE_FR
-  LANGUAGE= LC_ALL=$LOCALE_FR guile -s prog.scm 2 > prog.out 2>prog.err || { cat prog.err 1>&2; exit 1; }
+  LANGUAGE= LC_ALL=$LOCALE_FR guile -s prog.scm 2 > prog.out 2>prog.err || { cat prog.err 1>&2; Exit 1; }
   grep -v '^;;;' prog.err 1>&2
-  ${DIFF} prog.ok prog.out || exit 1
+  ${DIFF} prog.ok prog.out || Exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
   prepare_locale_ fr $LOCALE_FR_UTF8
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 guile -s prog.scm 2 > prog.out 2>prog.err || { cat prog.err 1>&2; exit 1; }
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 guile -s prog.scm 2 > prog.out 2>prog.err || { cat prog.err 1>&2; Exit 1; }
   grep -v '^;;;' prog.err 1>&2
-  ${DIFF} prog.oku prog.out || exit 1
+  ${DIFF} prog.oku prog.out || Exit 1
 fi
 
-exit 0
+Exit 0
diff --git a/gettext-tools/tests/lang-python-2 b/gettext-tools/tests/lang-python-2
--- a/gettext-tools/tests/lang-python-2
+++ b/gettext-tools/tests/lang-python-2
@@ -25,8 +25,8 @@ print gettext.gettext("%(oldCurrency)s is replaced by %(newCurrency)s.") \
 EOF
 
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.tmp --omit-header --no-location prog2.py || exit 1
-LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog2.py || Exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || Exit 1
 
 cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
@@ -44,7 +44,7 @@ msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} prog.ok prog.pot || exit 1
+${DIFF} prog.ok prog.pot || Exit 1
 
 cat <<\EOF > fr.po
 msgid ""
@@ -69,11 +69,11 @@ msgstr "%(newCurrency)s remplace %(oldCurrency)s."
 EOF
 
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
-LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || Exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || Exit 1
 
 : ${DIFF=diff}
-${DIFF} fr.po fr.po.new || exit 1
+${DIFF} fr.po fr.po.new || Exit 1
 
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
@@ -83,10 +83,10 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of python version 2.3 or newer.
 (python -V) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: python not found"; exit 77; }
+  || { echo "Skipping test: python not found"; Exit 77; }
 case `python -c 'import sys; print sys.hexversion >= 0x20300F0'` in
   1 | True) ;;
-  *) echo "Skipping test: python version too old"; exit 77;;
+  *) echo "Skipping test: python version too old"; Exit 77;;
 esac
 
 : ${DIFF=diff}
@@ -105,14 +105,14 @@ EOF
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
   prepare_locale_ fr $LOCALE_FR
-  LANGUAGE= LC_ALL=$LOCALE_FR python prog2.py 2 > prog.out || exit 1
-  ${DIFF} prog.ok prog.out || exit 1
+  LANGUAGE= LC_ALL=$LOCALE_FR python prog2.py 2 > prog.out || Exit 1
+  ${DIFF} prog.ok prog.out || Exit 1
 fi
 if test -z "$UTF8_LOCALE_UNSUPPORTED"; then
   if test $LOCALE_FR_UTF8 != none; then
     prepare_locale_ fr $LOCALE_FR_UTF8
-    LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 python prog2.py 2 > prog.out || exit 1
-    ${DIFF} prog.oku prog.out || exit 1
+    LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 python prog2.py 2 > prog.out || Exit 1
+    ${DIFF} prog.oku prog.out || Exit 1
   fi
   if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
     if test -f /usr/bin/localedef; then
@@ -120,7 +120,7 @@ if test -z "$UTF8_LOCALE_UNSUPPORTED"; then
     else
       echo "Skipping test: no french locale is supported"
     fi
-    exit 77
+    Exit 77
   fi
 else
   if test $LOCALE_FR = none; then
@@ -129,8 +129,8 @@ else
     else
       echo "Skipping test: no traditional french locale is supported"
     fi
-    exit 77
+    Exit 77
   fi
 fi
 
-exit 0
+Exit 0
