Import gettext-0.19.

diff --git a/gettext-tools/tests/lang-python-1 b/gettext-tools/tests/lang-python-1
--- a/gettext-tools/tests/lang-python-1
+++ b/gettext-tools/tests/lang-python-1
@@ -1,4 +1,5 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the Python language.
 
@@ -6,10 +7,6 @@
 # It looks like a bug in Python's gettext.py. This here is a quick workaround:
 UTF8_LOCALE_UNSUPPORTED=yes
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog1.py"
 cat <<\EOF > prog1.py
 import gettext
 
@@ -21,14 +18,10 @@ print gettext.gettext("%(oldCurrency)s is replaced by %(newCurrency)s.") \
       % { 'oldCurrency': "FF", 'newCurrency' : "EUR" }
 EOF
 
-tmpfiles="$tmpfiles l-python-1-prog.tmp l-python-1-prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-python-1-prog.tmp --omit-header --no-location prog1.py
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-python-1-prog.tmp > l-python-1-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o l-python-1-prog.tmp --omit-header --no-location prog1.py || exit 1
+LC_ALL=C tr -d '\r' < l-python-1-prog.tmp > l-python-1-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-python-1-prog.ok"
 cat <<EOF > l-python-1-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -41,7 +34,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} l-python-1-prog.ok l-python-1-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-python-1-fr.po"
 cat <<\EOF > l-python-1-fr.po
 msgid ""
 msgstr ""
@@ -57,17 +49,13 @@ msgid "%(oldCurrency)s is replaced by %(newCurrency)s."
 msgstr "%(newCurrency)s remplace %(oldCurrency)s."
 EOF
 
-tmpfiles="$tmpfiles l-python-1-fr.po.tmp l-python-1-fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-python-1-fr.po.tmp l-python-1-fr.po l-python-1-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-python-1-fr.po.tmp > l-python-1-fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-python-1-fr.po.tmp l-python-1-fr.po l-python-1-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-python-1-fr.po.tmp > l-python-1-fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} l-python-1-fr.po l-python-1-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles l-python-1"
 test -d l-python-1 || mkdir l-python-1
 test -d l-python-1/fr || mkdir l-python-1/fr
 test -d l-python-1/fr/LC_MESSAGES || mkdir l-python-1/fr/LC_MESSAGES
@@ -77,13 +65,12 @@ ${MSGFMT} -o l-python-1/fr/LC_MESSAGES/prog.mo l-python-1-fr.po
 
 # Test for presence of python version 2.0 or newer.
 (python -V) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: python not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: python not found"; exit 77; }
 case `python -c 'import sys; print sys.hexversion >= 0x20000F0'` in
   1 | True) ;;
-  *) echo "Skipping test: python version too old"; rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: python version too old"; exit 77;;
 esac
 
-tmpfiles="$tmpfiles l-python-1-prog.ok l-python-1-prog.oku l-python-1-prog.out"
 : ${DIFF=diff}
 cat <<\EOF > l-python-1-prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -111,7 +98,7 @@ if test -z "$UTF8_LOCALE_UNSUPPORTED"; then
     else
       echo "Skipping test: no french locale is supported"
     fi
-    rm -fr $tmpfiles; exit 77
+    exit 77
   fi
 else
   if test $LOCALE_FR = none; then
@@ -120,10 +107,8 @@ else
     else
       echo "Skipping test: no traditional french locale is supported"
     fi
-    rm -fr $tmpfiles; exit 77
+    exit 77
   fi
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext-tools/tests/lang-smalltalk b/gettext-tools/tests/lang-smalltalk
--- a/gettext-tools/tests/lang-smalltalk
+++ b/gettext-tools/tests/lang-smalltalk
@@ -1,13 +1,10 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the GNU smalltalk language.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: smalltalk.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.st"
 cat <<\EOF > prog.st
 PackageLoader fileInPackage: 'I18N' !
 
@@ -33,14 +30,10 @@ run
 Main new run!
 EOF
 
-tmpfiles="$tmpfiles l-smalltalk-prog.tmp l-smalltalk-prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-smalltalk-prog.tmp --omit-header --no-location prog.st
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-smalltalk-prog.tmp > l-smalltalk-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o l-smalltalk-prog.tmp --omit-header --no-location prog.st || exit 1
+LC_ALL=C tr -d '\r' < l-smalltalk-prog.tmp > l-smalltalk-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-smalltalk-prog.ok"
 cat <<EOF > l-smalltalk-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -59,7 +52,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} l-smalltalk-prog.ok l-smalltalk-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-smalltalk-fr.po"
 cat <<\EOF > l-smalltalk-fr.po
 msgid ""
 msgstr ""
@@ -82,17 +74,13 @@ msgid "%1 is replaced by %2."
 msgstr "%2 remplace %1."
 EOF
 
-tmpfiles="$tmpfiles l-smalltalk-fr.po.tmp l-smalltalk-fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-smalltalk-fr.po.tmp l-smalltalk-fr.po l-smalltalk-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-smalltalk-fr.po.tmp > l-smalltalk-fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-smalltalk-fr.po.tmp l-smalltalk-fr.po l-smalltalk-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-smalltalk-fr.po.tmp > l-smalltalk-fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} l-smalltalk-fr.po l-smalltalk-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles l-smalltalk"
 test -d l-smalltalk || mkdir l-smalltalk
 test -d l-smalltalk/fr || mkdir l-smalltalk/fr
 test -d l-smalltalk/fr/LC_MESSAGES || mkdir l-smalltalk/fr/LC_MESSAGES
@@ -102,13 +90,12 @@ ${MSGFMT} -o l-smalltalk/fr/LC_MESSAGES/prog.mo l-smalltalk-fr.po
 
 # Test for presence of gst version 2.0.6 or newer.
 (gst --version) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: gst not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: gst not found"; exit 77; }
 case `gst --version | sed -n -e 1p | sed -e 's/^[^0-9]*//'` in
   0.* | 1.* | 2.0 | 2.0.[0-5] | 2.1 | 2.1.[0-1])
-    echo "Skipping test: gst version too old"; rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: gst version too old"; exit 77;;
 esac
 
-tmpfiles="$tmpfiles l-smalltalk-prog.ok l-smalltalk-prog.oku l-smalltalk-prog.ok2 l-smalltalk-prog.oku2 l-smalltalk-prog.ok3 l-smalltalk-prog.oku3 l-smalltalk-prog.out"
 : ${DIFF=diff}
 cat <<\EOF > l-smalltalk-prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -150,9 +137,7 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext-tools/tests/lang-vala b/gettext-tools/tests/lang-vala
--- a/gettext-tools/tests/lang-vala
+++ b/gettext-tools/tests/lang-vala
@@ -1,13 +1,10 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the Vala language.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: vala.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles l-vala-prog.vala"
 cat <<\EOF > l-vala-prog.vala
 int main (string[] args) {
     Intl.setlocale (LocaleCategory.ALL, "");
@@ -22,21 +19,16 @@ EOF
 # Test for presence of valac.
 (valac --version) >/dev/null 2>/dev/null
 test $? -le 1 \
-  || { echo "Skipping test: valac not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: valac not found"; exit 77; }
 
-tmpfiles="$tmpfiles l-vala-prog.vala l-vala-prog.c l-vala-prog l-vala-prog.err"
 : ${VALAC=valac}
 ${VALAC} --Xcc=-DGETTEXT_PACKAGE=\"prog\" l-vala-prog.vala 2>l-vala-prog.err \
   || { cat l-vala-prog.err 1>&2; exit 1; }
 
-tmpfiles="$tmpfiles l-vala-prog.tmp l-vala-prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-vala-prog.tmp --omit-header --no-location l-vala-prog.vala
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-vala-prog.tmp > l-vala-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o l-vala-prog.tmp --omit-header --no-location l-vala-prog.vala || exit 1
+LC_ALL=C tr -d '\r' < l-vala-prog.tmp > l-vala-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-vala-prog.ok"
 cat <<EOF > l-vala-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -49,7 +41,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} l-vala-prog.ok l-vala-prog.pot || exit 1
 
-tmpfiles="$tmpfiles l-vala-fr.po"
 cat <<\EOF > l-vala-fr.po
 msgid ""
 msgstr "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -63,17 +54,13 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles l-vala-fr.po.tmp l-vala-fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-vala-fr.po.tmp l-vala-fr.po l-vala-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-vala-fr.po.tmp > l-vala-fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-vala-fr.po.tmp l-vala-fr.po l-vala-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-vala-fr.po.tmp > l-vala-fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} l-vala-fr.po l-vala-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles l-vala"
 test -d l-vala || mkdir l-vala
 test -d l-vala/fr || mkdir l-vala/fr
 test -d l-vala/fr/LC_MESSAGES || mkdir l-vala/fr/LC_MESSAGES
@@ -81,7 +68,6 @@ test -d l-vala/fr/LC_MESSAGES || mkdir l-vala/fr/LC_MESSAGES
 : ${MSGFMT=msgfmt}
 ${MSGFMT} -o l-vala/fr/LC_MESSAGES/prog.mo l-vala-fr.po
 
-tmpfiles="$tmpfiles l-vala-prog.ok l-vala-prog.oku l-vala-prog.out"
 : ${DIFF=diff}
 cat <<\EOF > l-vala-prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -116,9 +102,7 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
-
-rm -fr $tmpfiles
 
 exit 0
