1. makefiles support for locales 2. makefiles support for semistatic builds 3. version 1.1.6

diff --git a/poedit/configure b/poedit/configure
--- a/poedit/configure
+++ b/poedit/configure
@@ -22,7 +22,7 @@ ac_help="$ac_help
 ac_help="$ac_help
   --enable-debug          Enable debugging information"
 ac_help="$ac_help
-  --enable-semistatic          Link statically against wxWindows and libdb"
+  --enable-semistatic     Link statically against wxWindows and libdb"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -1881,118 +1881,19 @@ echo "$ac_t""$CPP" 1>&6
 
   USE_TRANSMEM=1
 
-  echo $ac_n "checking for db_create in -ldb-3.1""... $ac_c" 1>&6
-echo "configure:1886: checking for db_create in -ldb-3.1" >&5
-ac_lib_var=`echo db-3.1'_'db_create | sed 'y%./+-%__p_%'`
-if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  ac_save_LIBS="$LIBS"
-LIBS="-ldb-3.1  $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 1894 "configure"
-#include "confdefs.h"
-/* Override any gcc2 internal prototype to avoid an error.  */
-/* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
-char db_create();
-
-int main() {
-db_create()
-; return 0; }
-EOF
-if { (eval echo configure:1905: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=yes"
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=no"
-fi
-rm -f conftest*
-LIBS="$ac_save_LIBS"
-
-fi
-if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-  
-         DB_LIB=-ldb-3.1
-     
-else
-  echo "$ac_t""no" 1>&6
-
-         echo $ac_n "checking for db_create in -ldb""... $ac_c" 1>&6
-echo "configure:1927: checking for db_create in -ldb" >&5
-ac_lib_var=`echo db'_'db_create | sed 'y%./+-%__p_%'`
-if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  ac_save_LIBS="$LIBS"
-LIBS="-ldb  $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 1935 "configure"
-#include "confdefs.h"
-/* Override any gcc2 internal prototype to avoid an error.  */
-/* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
-char db_create();
-
-int main() {
-db_create()
-; return 0; }
-EOF
-if { (eval echo configure:1946: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=yes"
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=no"
-fi
-rm -f conftest*
-LIBS="$ac_save_LIBS"
-
-fi
-if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-  
-             DB_LIB=-ldb
-         
-else
-  echo "$ac_t""no" 1>&6
-
-             USE_TRANSMEM=0
-             echo "configure: warning: 
-
-*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
-
- Cannot find Berkeley DB 3.1, poEdit will build w/o translation memory feature!
-
-*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
-
-             " 1>&2
-         
-fi
-
-     
-fi
-
-
   ac_safe=`echo "db3/db.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for db3/db.h""... $ac_c" 1>&6
-echo "configure:1986: checking for db3/db.h" >&5
+echo "configure:1887: checking for db3/db.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1991 "configure"
+#line 1892 "configure"
 #include "confdefs.h"
 #include <db3/db.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1996: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1897: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2010,23 +1911,24 @@ if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   
         CXXFLAGS="$CXXFLAGS -DUSE_REDHAT_DB3"
+        DB3HEADER="db3/db.h"
      
 else
   echo "$ac_t""no" 1>&6
 
         ac_safe=`echo "db.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for db.h""... $ac_c" 1>&6
-echo "configure:2020: checking for db.h" >&5
+echo "configure:1922: checking for db.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2025 "configure"
+#line 1927 "configure"
 #include "confdefs.h"
 #include <db.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2030: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1932: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2047,12 +1949,13 @@ else
   echo "$ac_t""no" 1>&6
 
            USE_TRANSMEM=0
+           DB3HEADER="db.h"
            echo "$ac_t""not found" 1>&6
            echo "configure: warning: 
 
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
 
- Cannot find Berkeley DB 3.1, poEdit will build w/o translation memory feature!
+ Cannot find Berkeley DB 3.x, poEdit will build w/o translation memory feature!
 
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
 
@@ -2063,11 +1966,85 @@ fi
      
 fi
 
+     
+  
+  
+echo $ac_n "checking for library containing db_create""... $ac_c" 1>&6
+echo "configure:1974: checking for library containing db_create" >&5
+if eval "test \"`echo '$''{'ac_cv_search_db_create'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_func_search_save_LIBS="$LIBS"
+ac_cv_search_db_create="no"
+cat > conftest.$ac_ext <<EOF
+#line 1981 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char db_create();
+
+int main() {
+db_create()
+; return 0; }
+EOF
+if { (eval echo configure:1992: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  ac_cv_search_db_create="none required"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+fi
+rm -f conftest*
+test "$ac_cv_search_db_create" = "no" && for i in db-3.6 db-3.5 db-3.4 db-3.3 db-3.2 db-3.1 db; do
+LIBS="-l$i  $ac_func_search_save_LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 2003 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char db_create();
+
+int main() {
+db_create()
+; return 0; }
+EOF
+if { (eval echo configure:2014: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  ac_cv_search_db_create="-l$i"
+break
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+fi
+rm -f conftest*
+done
+LIBS="$ac_func_search_save_LIBS"
+fi
+
+echo "$ac_t""$ac_cv_search_db_create" 1>&6
+if test "$ac_cv_search_db_create" != "no"; then
+  test "$ac_cv_search_db_create" = "none required" || LIBS="$ac_cv_search_db_create $LIBS"
+  
+else :
+  
+         USE_TRANSMEM=0
+         echo "configure: warning: 
+
+*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
+
+ Cannot find Berkeley DB 3.x, poEdit will build w/o translation memory feature!
+
+*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
+
+         " 1>&2
+     
+fi
 
   if test x$USE_TRANSMEM != x0 ; then
       CXXFLAGS="$CXXFLAGS -DUSE_TRANSMEM"
   fi
-  LIBS="$LIBS $DB_LIB"
   CXXFLAGS="$CXXFLAGS $DB_INCLUDE"
 
     fi
@@ -2082,13 +2059,24 @@ else
   USE_WINDOWS_FALSE=
 fi
 
+CATALOGS_TO_INSTALL="install-poedit-catalogs"
+
 if test x$USE_SEMISTATIC = xyes ; then
-    POEDIT_WX_LIBS="$WX_LIBS_STATIC"
+    CATALOGS_TO_INSTALL="$CATALOGS_TO_INSTALL install-wxstd-catalogs"
+
+    
+
+            LIBS=`echo $LIBS | sed -e 's/\(-ldb[^ ]*\)/-Wl,-Bstatic \1 -Wl,-Bdynamic/g'`
+
+        POEDIT_WX_LIBS=`echo $WX_LIBS_STATIC | sed -e 's/\(-ltiff\|-ljpeg\)//g'`
+
+    
 else
     POEDIT_WX_LIBS="$WX_LIBS"
 fi
 
 CXXFLAGS="$CXXFLAGS $DEBUG_FLAGS $WX_CXXFLAGS \"-DPOEDIT_PREFIX=\\\"$prefix\\\"\""
+
 
 
 
@@ -2220,6 +2208,7 @@ trap 'rm -fr `echo "
          extras/wx-contrib/src/xrc/expat/Makefile
          src/Makefile
          src/resources/Makefile
+         locales/Makefile
          docs/Makefile
          install/Makefile
          install/poedit.keys
@@ -2310,6 +2299,7 @@ s%@RESCOMP@%$RESCOMP%g
 s%@WX_CONFIG_NAME@%$WX_CONFIG_NAME%g
 s%@POEDIT_WX_LIBS@%$POEDIT_WX_LIBS%g
 s%@RC_WX_INCLUDES@%$RC_WX_INCLUDES%g
+s%@CATALOGS_TO_INSTALL@%$CATALOGS_TO_INSTALL%g
 
 CEOF
 EOF
@@ -2360,6 +2350,7 @@ CONFIG_FILES=\${CONFIG_FILES-"Makefile
          extras/wx-contrib/src/xrc/expat/Makefile
          src/Makefile
          src/resources/Makefile
+         locales/Makefile
          docs/Makefile
          install/Makefile
          install/poedit.keys
