better check for libdb3

diff --git a/poedit/configure b/poedit/configure
--- a/poedit/configure
+++ b/poedit/configure
@@ -1734,8 +1734,91 @@ echo "$ac_t""$CPP" 1>&6
 
 
   USE_TRANSMEM=1
-  echo $ac_n "checking for db_create in -ldb-3.1""... $ac_c" 1>&6
-echo "configure:1739: checking for db_create in -ldb-3.1" >&5
+
+  echo $ac_n "checking for db_create in -ldb-3.3""... $ac_c" 1>&6
+echo "configure:1740: checking for db_create in -ldb-3.3" >&5
+ac_lib_var=`echo db-3.3'_'db_create | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-ldb-3.3  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 1748 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char db_create();
+
+int main() {
+db_create()
+; return 0; }
+EOF
+if { (eval echo configure:1759: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  
+         DB_LIB=-ldb-3.3
+     
+else
+  echo "$ac_t""no" 1>&6
+
+      echo $ac_n "checking for db_create in -ldb-3.2""... $ac_c" 1>&6
+echo "configure:1781: checking for db_create in -ldb-3.2" >&5
+ac_lib_var=`echo db-3.2'_'db_create | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-ldb-3.2  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 1789 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char db_create();
+
+int main() {
+db_create()
+; return 0; }
+EOF
+if { (eval echo configure:1800: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  
+             DB_LIB=-ldb-3.2
+         
+else
+  echo "$ac_t""no" 1>&6
+
+          echo $ac_n "checking for db_create in -ldb-3.1""... $ac_c" 1>&6
+echo "configure:1822: checking for db_create in -ldb-3.1" >&5
 ac_lib_var=`echo db-3.1'_'db_create | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1743,7 +1826,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ldb-3.1  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1747 "configure"
+#line 1830 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1754,7 +1837,7 @@ int main() {
 db_create()
 ; return 0; }
 EOF
-if { (eval echo configure:1758: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1841: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1770,13 +1853,13 @@ fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   
-         DB_LIB=-ldb-3.1
-     
+                 DB_LIB=-ldb-3.1
+             
 else
   echo "$ac_t""no" 1>&6
 
-         echo $ac_n "checking for db_create in -ldb""... $ac_c" 1>&6
-echo "configure:1780: checking for db_create in -ldb" >&5
+                 echo $ac_n "checking for db_create in -ldb""... $ac_c" 1>&6
+echo "configure:1863: checking for db_create in -ldb" >&5
 ac_lib_var=`echo db'_'db_create | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1784,7 +1867,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ldb  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1788 "configure"
+#line 1871 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1795,7 +1878,7 @@ int main() {
 db_create()
 ; return 0; }
 EOF
-if { (eval echo configure:1799: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1882: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1811,21 +1894,27 @@ fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   
-             DB_LIB=-ldb
-         
+                     DB_LIB=-ldb
+                 
 else
   echo "$ac_t""no" 1>&6
 
-             USE_TRANSMEM=0
-             echo "configure: warning: 
+                     USE_TRANSMEM=0
+                     echo "configure: warning: 
 
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
 
- Cannot find Berkeley DB 3.1, poEdit will build w/o translation memory feature!
+ Cannot find Berkeley DB 3.x, poEdit will build w/o translation memory feature!
 
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
 
-             " 1>&2
+                     " 1>&2
+                 
+fi
+
+             
+fi
+
          
 fi
 
@@ -1835,17 +1924,17 @@ fi
 
   ac_safe=`echo "db3/db.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for db3/db.h""... $ac_c" 1>&6
-echo "configure:1839: checking for db3/db.h" >&5
+echo "configure:1928: checking for db3/db.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1844 "configure"
+#line 1933 "configure"
 #include "confdefs.h"
 #include <db3/db.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1849: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1938: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -1869,17 +1958,17 @@ else
 
         ac_safe=`echo "db.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for db.h""... $ac_c" 1>&6
-echo "configure:1873: checking for db.h" >&5
+echo "configure:1962: checking for db.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1878 "configure"
+#line 1967 "configure"
 #include "confdefs.h"
 #include <db.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1883: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1972: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -1905,7 +1994,7 @@ else
 
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
 
- Cannot find Berkeley DB 3.1, poEdit will build w/o translation memory feature!
+ Cannot find Berkeley DB 3.x, poEdit will build w/o translation memory feature!
 
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** 
 
