Improve OTA action's handling of errors
Improve the GitHub action for uploading OTA translation updates:

- If a PO file has errors, remove the offending entries, but don't block
  the entire file's upload

- Report errors in a structured way that makes it easier to identify
  the strings at Crowdin

As a side-effect, merge the workflow into a single job, because
parallelizing it was actually more time consuming due to the need to
download gettext dependency.

diff --git a/.github/workflows/build-ota-updates.yml b/.github/workflows/build-ota-updates.yml
--- a/.github/workflows/build-ota-updates.yml
+++ b/.github/workflows/build-ota-updates.yml
@@ -7,12 +7,17 @@ on:
     - cron:  '11 10 * * *'
 
 jobs:
-  download-translations:
-    name: Get Crowdin translations
+  build-ota-translations:
+    name: Build OTA translations
     runs-on: ubuntu-latest
-
     steps:
     - uses: actions/checkout@v4
+    - name: Install GNU gettext
+      run: sudo apt-get install gettext
+    - name: Install uv
+      uses: astral-sh/setup-uv@v5
+      with:
+        cache-dependency-glob: "scripts/check-translations.py"
     - name: Install Crowdin CLI
       run: npm i -g @crowdin/cli
     - name: Download latest translations from Crowdin
@@ -20,43 +25,12 @@ jobs:
         echo 'api_token: "${{secrets.CROWDIN_PERSONAL_TOKEN}}"' >>crowdin.yaml
         crowdin download
         rm crowdin.yaml
-    - uses: actions/upload-artifact@v4
-      with:
-        name: translations
-        path: locales/*.po
-
-  check-po-validity:
-    name: Check translations
-    runs-on: ubuntu-latest
-    needs: download-translations
-    steps:
-    - uses: actions/download-artifact@v4
-      with:
-        name: translations
-        path: locales
-    - name: Install GNU gettext
-      run: sudo apt-get install gettext
-    - name: Check PO files with msgfmt -v -c
-      run: |
-        for i in locales/*.po ; do
-          echo "checking $i..."
-          msgfmt -v -c -o /dev/null $i
-        done
-
-  build-ota-translations:
-    name: Build OTA translations
-    runs-on: ubuntu-latest
-    needs: download-translations
-    steps:
-    - uses: actions/checkout@v4
-    - uses: actions/download-artifact@v4
-      with:
-        name: translations
-        path: locales
-    - name: Install GNU gettext
-      run: sudo apt-get install gettext
     - name: Build OTA updates
       run: scripts/build-ota-translations.sh
+    - uses: actions/upload-artifact@v4
+      with:
+        name: ota-update
+        path: ota-update.tar
     - name: Upload OTA updates
       run: |
         VERSION=$(sed -n -e 's/.*POEDIT_VERSION_SHORT.* "\(.*\)".*/\1/p' src/version.h)
@@ -65,7 +39,13 @@ jobs:
         cat response
         modified=$(echo `jq -r '.modified[]' < response`)
         if [ -n "$modified" ] ; then
-          echo "::notice title=Translations updated::Updated translation files: $modified"
+          echo "::notice title=Translations updated::Updated files: $modified"
         else
           echo "::notice title=No updates::No translations were updated."
+        fi
+    - name: Check for PO compilation errors
+      run: |
+        if [ -f ota-had-errors ]; then
+          echo "::warning::Some strings were removed from OTA translations due to errors."
+          exit 1
         fi
